/*
 * This file is generated by jOOQ.
 */
package co.db.jooq.tables.records;


import co.db.jooq.tables.Saiyans;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SaiyansRecord extends UpdatableRecordImpl<SaiyansRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>saiyans.saiyan_id</code>.
     */
    public SaiyansRecord setSaiyanId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_id</code>.
     */
    public Integer getSaiyanId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>saiyans.saiyan_name</code>.
     */
    public SaiyansRecord setSaiyanName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_name</code>.
     */
    public String getSaiyanName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>saiyans.saiyan_gender</code>.
     */
    public SaiyansRecord setSaiyanGender(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_gender</code>.
     */
    public String getSaiyanGender() {
        return (String) get(2);
    }

    /**
     * Setter for <code>saiyans.saiyan_blood</code>.
     */
    public SaiyansRecord setSaiyanBlood(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_blood</code>.
     */
    public String getSaiyanBlood() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Saiyans.SAIYANS.SAIYAN_ID;
    }

    @Override
    public Field<String> field2() {
        return Saiyans.SAIYANS.SAIYAN_NAME;
    }

    @Override
    public Field<String> field3() {
        return Saiyans.SAIYANS.SAIYAN_GENDER;
    }

    @Override
    public Field<String> field4() {
        return Saiyans.SAIYANS.SAIYAN_BLOOD;
    }

    @Override
    public Integer component1() {
        return getSaiyanId();
    }

    @Override
    public String component2() {
        return getSaiyanName();
    }

    @Override
    public String component3() {
        return getSaiyanGender();
    }

    @Override
    public String component4() {
        return getSaiyanBlood();
    }

    @Override
    public Integer value1() {
        return getSaiyanId();
    }

    @Override
    public String value2() {
        return getSaiyanName();
    }

    @Override
    public String value3() {
        return getSaiyanGender();
    }

    @Override
    public String value4() {
        return getSaiyanBlood();
    }

    @Override
    public SaiyansRecord value1(Integer value) {
        setSaiyanId(value);
        return this;
    }

    @Override
    public SaiyansRecord value2(String value) {
        setSaiyanName(value);
        return this;
    }

    @Override
    public SaiyansRecord value3(String value) {
        setSaiyanGender(value);
        return this;
    }

    @Override
    public SaiyansRecord value4(String value) {
        setSaiyanBlood(value);
        return this;
    }

    @Override
    public SaiyansRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SaiyansRecord
     */
    public SaiyansRecord() {
        super(Saiyans.SAIYANS);
    }

    /**
     * Create a detached, initialised SaiyansRecord
     */
    public SaiyansRecord(Integer saiyanId, String saiyanName, String saiyanGender, String saiyanBlood) {
        super(Saiyans.SAIYANS);

        setSaiyanId(saiyanId);
        setSaiyanName(saiyanName);
        setSaiyanGender(saiyanGender);
        setSaiyanBlood(saiyanBlood);
    }
}
