/*
 * This file is generated by jOOQ.
 */
package co.db.jooq;


import co.db.jooq.tables.Saiyans;
import co.db.jooq.tables.records.SaiyansRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SaiyansRecord> KEY_SAIYANS_PRIMARY = Internal.createUniqueKey(Saiyans.SAIYANS, DSL.name("KEY_saiyans_PRIMARY"), new TableField[] { Saiyans.SAIYANS.SAIYAN_ID }, true);
    public static final UniqueKey<SaiyansRecord> KEY_SAIYANS_SAIYAN_ID = Internal.createUniqueKey(Saiyans.SAIYANS, DSL.name("KEY_saiyans_saiyan_id"), new TableField[] { Saiyans.SAIYANS.SAIYAN_ID }, true);
}
