/*
 * This file is generated by jOOQ.
 */
package co.db.jooq;


import co.db.jooq.tables.Saiyans;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>saiyans</code>.
     */
    public static final Saiyans SAIYANS = Saiyans.SAIYANS;
}
