/*
 * This file is generated by jOOQ.
 */
package co.db.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saiyans implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer saiyanId;
    private String  saiyanName;
    private String  saiyanGender;
    private String  saiyanBlood;

    public Saiyans() {}

    public Saiyans(Saiyans value) {
        this.saiyanId = value.saiyanId;
        this.saiyanName = value.saiyanName;
        this.saiyanGender = value.saiyanGender;
        this.saiyanBlood = value.saiyanBlood;
    }

    public Saiyans(
        Integer saiyanId,
        String  saiyanName,
        String  saiyanGender,
        String  saiyanBlood
    ) {
        this.saiyanId = saiyanId;
        this.saiyanName = saiyanName;
        this.saiyanGender = saiyanGender;
        this.saiyanBlood = saiyanBlood;
    }

    /**
     * Getter for <code>saiyans.saiyan_id</code>.
     */
    public Integer getSaiyanId() {
        return this.saiyanId;
    }

    /**
     * Setter for <code>saiyans.saiyan_id</code>.
     */
    public Saiyans setSaiyanId(Integer saiyanId) {
        this.saiyanId = saiyanId;
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_name</code>.
     */
    public String getSaiyanName() {
        return this.saiyanName;
    }

    /**
     * Setter for <code>saiyans.saiyan_name</code>.
     */
    public Saiyans setSaiyanName(String saiyanName) {
        this.saiyanName = saiyanName;
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_gender</code>.
     */
    public String getSaiyanGender() {
        return this.saiyanGender;
    }

    /**
     * Setter for <code>saiyans.saiyan_gender</code>.
     */
    public Saiyans setSaiyanGender(String saiyanGender) {
        this.saiyanGender = saiyanGender;
        return this;
    }

    /**
     * Getter for <code>saiyans.saiyan_blood</code>.
     */
    public String getSaiyanBlood() {
        return this.saiyanBlood;
    }

    /**
     * Setter for <code>saiyans.saiyan_blood</code>.
     */
    public Saiyans setSaiyanBlood(String saiyanBlood) {
        this.saiyanBlood = saiyanBlood;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Saiyans other = (Saiyans) obj;
        if (saiyanId == null) {
            if (other.saiyanId != null)
                return false;
        }
        else if (!saiyanId.equals(other.saiyanId))
            return false;
        if (saiyanName == null) {
            if (other.saiyanName != null)
                return false;
        }
        else if (!saiyanName.equals(other.saiyanName))
            return false;
        if (saiyanGender == null) {
            if (other.saiyanGender != null)
                return false;
        }
        else if (!saiyanGender.equals(other.saiyanGender))
            return false;
        if (saiyanBlood == null) {
            if (other.saiyanBlood != null)
                return false;
        }
        else if (!saiyanBlood.equals(other.saiyanBlood))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.saiyanId == null) ? 0 : this.saiyanId.hashCode());
        result = prime * result + ((this.saiyanName == null) ? 0 : this.saiyanName.hashCode());
        result = prime * result + ((this.saiyanGender == null) ? 0 : this.saiyanGender.hashCode());
        result = prime * result + ((this.saiyanBlood == null) ? 0 : this.saiyanBlood.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Saiyans (");

        sb.append(saiyanId);
        sb.append(", ").append(saiyanName);
        sb.append(", ").append(saiyanGender);
        sb.append(", ").append(saiyanBlood);

        sb.append(")");
        return sb.toString();
    }
}
